### PR TITLE
Add Telegram room to README.md

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
Dear,
Thank you for your project.
Please merge my commit to add biggest React.js Telegram group (over 500 members).

### CODE REVIEW

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by RReverser** [comment]
@DenisIzmaylov Sorry, but it's unrelated. This is not a catalogue of links or even a "project", just a fictional repo for the Gitter chat.

**Comment by koistya** [comment]
What @RReverser said ^^

**Comment by DenisIzmaylov** [comment]
I did not notice something about it's for Gitter chats only:

image

**Comment by RReverser** [comment]
That means they're actual chat rooms, not repos :)

**Comment by DenisIzmaylov** [comment]
Ok, I realize that. Thank you.

On Sunday, May 8, 2016, Ingvar Stepanyan notifications@github.com wrote:

> That means they're actual chat rooms, not repos :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/chat-rooms/reactjs/pull/2#issuecomment-217719981

## 

Sent from Gmail Mobile

**Pull request closed without merging**
